### ISSUE TITLE
Error while testing react app with awsui components

### ISSUE THREAD

**Issue by AndresPope** [aws/awsui-documentation#11]
hello, i am using awsui-components in my project, when i´m going to test some code, jest always failed with the code that have awsui in there, but when i try changing to material-ui, the result is always success.

Jest throw me some steps that i have to follow, i already followed the steps and the problem keeps there.

Someone knows why is that happening?

<img width="674" alt="the problem" src="https://user-images.githubusercontent.com/52660405/117919407-8b8b0a00-b2b2-11eb-9f66-f21f0a9e7c7e.png">

**Comment by gethinwebster** [comment]
Hi,

The awsui package uses ES6 import/export syntax, so you need to configure jest to process these files appropriately. You can do this using the [transformIgnorePatterns](https://jestjs.io/docs/configuration#transformignorepatterns-arraystring) flag - jest's default ignore pattern includes all files within `node_modules`, so you should instead pass something like `node_modules/(?!(@awsui)/).+\\.(js|jsx|ts|tsx)$` to allow any modules under @awsui to be transformed.

You can see an example here of this in use here: https://github.com/aws/awsui-documentation/blob/main/example/package.json#L19

Hope that helps!

**Comment by CharlesStover** [comment]
I wrote the article [Testing AWS UI components with Jest](https://charles-stover.medium.com/testing-aws-ui-components-with-jest-6983a7f8e985) to walk through this configuration.

For an example working in production, see [`babel.config.js`](https://github.com/CharlesStover/charlesstover.com/blob/b2538d89bbdc9ce1f587bf5464c5f7fcbba91aa5/babel.config.cjs) and [`jest.config.js`](https://github.com/CharlesStover/charlesstover.com/blob/b2538d89bbdc9ce1f587bf5464c5f7fcbba91aa5/jest.config.js#L10).

This does require that I have Babel installed even though it's an otherwise TypeScript project.
