### ISSUE TITLE
Expose `ref` to Popover Component

### ISSUE THREAD

**Issue by solamanhuq** [aws/awsui-documentation#57]
**Describe the bug**
I'd like to manually close the Popover on a timeout. I can see that `InternalPopover` accepts `ref` as input and attaches `dismissPopover`:

```javascript
function InternalPopover(_a, ref) {
    ...
    var onDismiss = useCallback(function () {
        setVisible(false);
    }, []);
    ...
    useImperativeHandle(ref, function () { return ({
        dismissPopover: onDismiss
    }); });
}
```
Should be straightforward to expose this at the Top level?

**To Reproduce**
**Reproduction link**

**Expected behavior**
I should be able to use `ref` to disable a Popover:

```javascript
import { useState, useEffect, useRef } from 'react'
import { Button, Popover, StatusIndicator } from '@awsui/components-react'
const MyComponent = () => {
  const [isOpen, setIsOpen] = useState(false)
  const inputRef = useRef()

  useEffect(() => {
    if (!isOpen) {
      return
    }
    setTimeout(() => {
      setIsOpen(false)
      inputRef.current.dismissPopover()
    }, 2000)
  }, [isOpen])

  return (
    <Popover
      dismissButton={false}
      position="top"
      size="small"
      triggerType="custom"
      ref={inputRef}
      content={
        <StatusIndicator type="success">
          open
        </StatusIndicator>
      }
    >
      <Button onClick={() => setIsOpen(true)}>
        Click me!
      </Button>
    </Popover>
  )
}
```

**Screenshots**

**Environment (please complete the following information):**
 - OS: Monterey 12.5
 - Browser: chrome
 - Version 105
 - @awsui/components-react: 3.0.396

**Comment by connorlanigan** [comment]
Hello,

the Popover component intentionally does not support automatically closing it, because there are accessibility concerns with automatically removing content from the screen.

You can read more about this in the WCAG guidelines about the _"Timing Adjustable"_ requirement: https://www.w3.org/WAI/WCAG21/Understanding/timing-adjustable.html

**Comment by solamanhuq** [comment]
Thanks for the reply. I can see why the library would wish to hide that in the external popover.
My use case is a copy icon, where the popover says "copied!" I wonder if that goes against the WCAG guidelines?

In any case, I'm still able to leverage the `InternalPopover`, so this isn't necessarily a blocker if I still want to include a timer.

**Comment by solamanhuq** [comment]
Actually, I'm reopening because I want _some_ way of syncing this with other displays on the page.
Basically I am considering github's "copy code" widget. When clicked, the copy icon transforms into a green checkmark & the popover is displayed.

I think having both of those changes is good for UI. Now if `ref.dismissPopover` is not exposed, could we alternatively expose a `onDismissed` hook, so that I can change the checkmark back to the copy icon?

**Comment by connorlanigan** [comment]
> My use case is a copy icon, where the popover says "copied!" I wonder if that goes against the WCAG guidelines?

We're not an authoritative source on WCAG requirements / interpretations. As far as I can personally tell, the use case you describe does not seem to overlap with one of the six criteria described in the link I shared above. I'd recommend to check with an accessibility expert for a reliable answer to that question. 

---


Note that the `InternalPopover` is (as the name already says) an internal component, and thus not covered by our API contract. By using it, your application may break at any time.

---

For the `onDismiss` event, I recommend to [open a feature request in the `cloudscape-design/components` repo](https://github.com/cloudscape-design/components/issues/new?assignees=&labels=enhancement&template=2_feature_request.yaml&title=%5BFeature+Request%5D%3A+) for that with a description of your use case, so that we can collect feedback and prioritise the request accordingly.

**Comment by solamanhuq** [comment]
got it. You are right and I switched approaches. and I opened a feature request.

Thanks!
