### ISSUE TITLE
AppLayout Navigation Drawer Close button styles

### ISSUE THREAD

**Issue by ColadaFF** [aws/awsui-documentation#9]
Hi there,

I've been trying to implement a user interface that is similar to the AWS console, with the header and the content using AppLayout, however, the header gets on top of the buttons of the Navigation and Tools drawer and there is no way that I can access them to change the css```top: 0``` property of the buttons.

Not even with the css```padding-top: 41px```as the AWS console does.

Here is an example: https://codesandbox.io/s/trusting-germain-3u73m?file=/src/App.js

Thanks!

**Comment by koiker** [comment]
Did you fixed you example?
To me looks like the navbar is correctly positioned on top of the AppLayout

**Comment by gethinwebster** [comment]
The codesandbox example linked above currently works correctly because the "Some bar" element matches the [default AppLayout headerSelector value](https://github.com/aws/awsui-documentation/blob/main/components/app-layout.md#headerselector) of `#b #h`, and therefore AppLayout can position itself around the bar.
